In [3]:
import numpy as np

from PIL import Image, ImageDraw
import torch
import torchvision
from IPython.display import display

np.random.seed(42)

In [4]:
train_Images_folder = '/Users/abdulrehman/Desktop/SML/WIDER_train/images/'
test_Images_folder = '/Users/abdulrehman/Desktop/SML/WIDER_val/images/'
train_bbx = '/Users/abdulrehman/Desktop/SML/wider_face_split/wider_face_train_bbx_gt.txt'
test_bbx = '/Users/abdulrehman/Desktop/SML/wider_face_split/wider_face_val_bbx_gt.txt'
data_folder = '/Users/abdulrehman/Desktop/SML/Faces'

Need to remove occlusion
need to remove invalid images

In [8]:
def create_data_dict(bbx_path,images_path):
    data = {}
    with open(bbx_path, 'r') as file:
        while True:
            line = file.readline()[:-1]#reads the image path
            if not line: break
            faces = []
            n = int(file.readline())#reads the number of bounding boxes present in the image at Path(line)
            check_valid = 1
            im = Image.open(images_path+line)
            l,w,_ = np.array(im).shape
            if n>0:
                while n>0:
                    #reads bounding boxes values and types
                    v = np.fromstring(file.readline(), dtype = float, sep=' ')
                    if check_valid ==1:
                    #if not clear or not valid or contains heavy occlusion do not consider
                        if v[4]!=0 or v[7]==1 or v[8]==2:
                            check_valid = 0
                        area = v[2]*v[3]
                        if area<100:
                            check_valid = 0
                        faces.append([v[0]/w, v[1]/l, v[2]/w, v[3]/l])
                    n-=1
                if check_valid:
                    data[line]=np.array(faces)
                    print(data[line])
            else: line = file.readline()
    
    return data

In [9]:
train_data = create_data_dict(train_bbx,train_Images_folder)

# test_data = create_data_dict(test_bbx,test_Images_folder)

[[0.43847656 0.23826715 0.11914062 0.10758123]]
[[0.35253906 0.06843575 0.25683594 0.23673184]]
[[0.56933594 0.49348958 0.05566406 0.08072917]
 [0.66015625 0.38932292 0.04394531 0.078125  ]
 [0.6015625  0.35807292 0.03808594 0.05338542]
 [0.60253906 0.29166667 0.03613281 0.04817708]
 [0.44238281 0.3828125  0.04296875 0.06901042]
 [0.35253906 0.36588542 0.03222656 0.05598958]
 [0.36523438 0.49479167 0.04882812 0.07161458]
 [0.24414062 0.5390625  0.04101562 0.06901042]
 [0.47363281 0.54557292 0.046875   0.08463542]]
[[0.28710938 0.18951358 0.44433594 0.36765635]]
[[0.51953125 0.16       0.21386719 0.27333333]]
[[0.42871094 0.12880396 0.18066406 0.17975938]]
[[0.26660156 0.21289062 0.26953125 0.2421875 ]]
[[0.20214844 0.29882812 0.32226562 0.28710938]]
[[0.76269531 0.50065104 0.06152344 0.06445312]]
[[0.32421875 0.16666667 0.20507812 0.38541667]
 [0.52929688 0.30208333 0.1796875  0.34635417]]
[[0.34082031 0.13103953 0.16699219 0.16178624]]
[[0.09082031 0.11523929 0.10351562 0.08375315]
 [

[[0.44433594 0.15469974 0.08496094 0.08224543]]
[[0.39453125 0.10875332 0.08984375 0.16976127]]
[[0.56445312 0.1294964  0.13867188 0.29064748]
 [0.453125   0.49784173 0.12304688 0.21007194]
 [0.21289062 0.2676259  0.125      0.24460432]]
[[0.34570312 0.22395833 0.07617188 0.16666667]]
[[0.36914062 0.20572917 0.29492188 0.58333333]]
[[0.3984375  0.28385417 0.06835938 0.13541667]]
[[0.25976562 0.16550117 0.31445312 0.56410256]]
[[0.20507812 0.17149758 0.06445312 0.13285024]
 [0.69726562 0.14009662 0.06445312 0.16183575]]
[[0.35546875 0.21752266 0.20703125 0.28600201]]
[[0.18359375 0.35202086 0.07421875 0.12255541]
 [0.6953125  0.39895698 0.07617188 0.12255541]]
[[0.35351562 0.30088496 0.0546875  0.15929204]
 [0.47460938 0.28672566 0.05273438 0.14513274]
 [0.62304688 0.28318584 0.05273438 0.14159292]]
[[0.20800781 0.14648438 0.24902344 0.20898438]]
[[0.60351562 0.10344828 0.08203125 0.14854111]
 [0.76367188 0.14323607 0.08789062 0.18567639]
 [0.140625   0.0530504  0.0625     0.25464191]]


[[0.21582031 0.25759577 0.04492188 0.07926024]
 [0.28808594 0.28137384 0.04003906 0.07926024]
 [0.70605469 0.33817701 0.04003906 0.07926024]
 [0.42089844 0.31307794 0.04003906 0.07793923]
 [0.47167969 0.35535007 0.04492188 0.06340819]
 [0.50292969 0.29062087 0.02929688 0.06208719]
 [0.51757812 0.22060766 0.0390625  0.08058124]]
[[0.45898438 0.29154519 0.1328125  0.25655977]]
[[0.34375    0.00877193 0.19726562 0.44736842]]
[[0.62011719 0.22148541 0.03710938 0.06763926]
 [0.71484375 0.22413793 0.0390625  0.06100796]
 [0.74316406 0.26923077 0.01757812 0.03846154]
 [0.59375    0.29310345 0.015625   0.02387268]
 [0.86132812 0.22148541 0.02539062 0.05702918]]
[[0.19433594 0.08333333 0.04980469 0.09356725]
 [0.30175781 0.34356725 0.03320312 0.06871345]
 [0.48046875 0.27631579 0.0390625  0.07163743]
 [0.66308594 0.3128655  0.03515625 0.0628655 ]
 [0.79785156 0.25       0.03808594 0.07163743]
 [0.89648438 0.24269006 0.04101562 0.0745614 ]
 [0.875      0.26608187 0.05273438 0.04678363]]
[[0.2128

[[0.10839844 0.10183486 0.11621094 0.15229358]
 [0.23925781 0.18348624 0.13769531 0.1559633 ]
 [0.31640625 0.06880734 0.1328125  0.13302752]
 [0.41601562 0.1266055  0.14355469 0.16972477]
 [0.54492188 0.1        0.1328125  0.20917431]]
[[0.10742188 0.3318649  0.06445312 0.13509545]
 [0.31640625 0.30249633 0.05664062 0.12041116]
 [0.47460938 0.38472834 0.05859375 0.13803231]
 [0.6171875  0.37885463 0.06445312 0.13509545]
 [0.8046875  0.27606461 0.0625     0.14096916]]
[[0.30078125 0.36200257 0.02636719 0.04749679]
 [0.31152344 0.42233633 0.03027344 0.05134788]
 [0.35351562 0.41463415 0.02832031 0.0449294 ]
 [0.37890625 0.37098845 0.02441406 0.04621309]
 [0.41503906 0.37483954 0.01953125 0.03851091]
 [0.43457031 0.40821566 0.02246094 0.03722721]
 [0.46777344 0.41591784 0.03710938 0.05776637]
 [0.49316406 0.37869063 0.02539062 0.04621309]
 [0.54492188 0.39922978 0.02832031 0.05391528]
 [0.5703125  0.35943517 0.02539062 0.03979461]
 [0.4609375  0.49422336 0.03515625 0.06546855]
 [0.5751953

[[0.60644531 0.68281938 0.04980469 0.0866373 ]
 [0.59277344 0.24522761 0.05078125 0.08370044]
 [0.69042969 0.05580029 0.05371094 0.09397944]
 [0.45214844 0.06754772 0.05175781 0.09838473]
 [0.45703125 0.34801762 0.046875   0.09838473]
 [0.28320312 0.34948605 0.046875   0.07782673]
 [0.26464844 0.1174743  0.04785156 0.09397944]
 [0.15917969 0.10279001 0.05078125 0.09251101]]
[[0.01171875 0.03258656 0.3046875  0.90835031]
 [0.31835938 0.00407332 0.3046875  0.89613035]]
[[0.1953125  0.32081911 0.11328125 0.17064846]
 [0.171875   0.10011377 0.08789062 0.15699659]
 [0.25390625 0.1069397  0.0703125  0.12059158]
 [0.38671875 0.0887372  0.07617188 0.11831627]
 [0.46679688 0.22298066 0.06640625 0.10466439]
 [0.56054688 0.1592719  0.0703125  0.12741752]
 [0.6328125  0.16609784 0.09179688 0.13651877]
 [0.73828125 0.17292378 0.11523438 0.16837315]]
[[0.42773438 0.27083333 0.17578125 0.2578125 ]]
[[0.1484375  0.5136742  0.125      0.13793103]
 [0.21289062 0.35671819 0.11328125 0.11414982]
 [0.32421

[[0.46289062 0.04234528 0.12304688 0.28664495]]
[[0.28808594 0.23446894 0.4375     0.37341349]]
[[0.19042969 0.08984375 0.03808594 0.07291667]
 [0.22363281 0.16536458 0.04199219 0.078125  ]
 [0.34472656 0.07421875 0.03808594 0.0703125 ]
 [0.34960938 0.16276042 0.04199219 0.07421875]
 [0.20898438 0.28385417 0.04492188 0.078125  ]
 [0.33691406 0.29296875 0.04003906 0.078125  ]
 [0.48144531 0.18619792 0.03710938 0.06770833]
 [0.49902344 0.06901042 0.03710938 0.07421875]
 [0.49023438 0.31770833 0.04394531 0.07161458]
 [0.65722656 0.10026042 0.03515625 0.0703125 ]
 [0.79980469 0.11588542 0.04003906 0.06901042]
 [0.75195312 0.17578125 0.04296875 0.078125  ]
 [0.62011719 0.16927083 0.046875   0.08072917]
 [0.63574219 0.32291667 0.04394531 0.078125  ]
 [0.77246094 0.26692708 0.04589844 0.08333333]]
[[0.1484375  0.23177083 0.09375    0.16927083]
 [0.32617188 0.37239583 0.08203125 0.14583333]
 [0.48828125 0.33333333 0.06445312 0.12760417]
 [0.625      0.33072917 0.07421875 0.12239583]
 [0.761718

[[0.1875     0.1484375  0.0703125  0.140625  ]
 [0.37890625 0.25520833 0.07617188 0.13802083]
 [0.57226562 0.29427083 0.0859375  0.15885417]
 [0.82226562 0.3203125  0.0546875  0.09114583]]
[[0.75       0.31640625 0.04003906 0.06380208]
 [0.67773438 0.296875   0.04101562 0.06119792]
 [0.56445312 0.31640625 0.03710938 0.0625    ]
 [0.52832031 0.265625   0.04003906 0.05989583]
 [0.46386719 0.31119792 0.03320312 0.0625    ]
 [0.39550781 0.30729167 0.03808594 0.05338542]
 [0.3125     0.26822917 0.0390625  0.06119792]
 [0.23535156 0.296875   0.03222656 0.04947917]
 [0.18066406 0.2421875  0.0390625  0.05729167]]
[[0.31445312 0.09505208 0.04394531 0.07552083]
 [0.49902344 0.08984375 0.04589844 0.07942708]
 [0.61523438 0.09244792 0.04980469 0.08854167]
 [0.45019531 0.16927083 0.04394531 0.08984375]
 [0.50488281 0.2265625  0.04980469 0.09375   ]
 [0.58105469 0.33333333 0.05175781 0.09244792]
 [0.6328125  0.20052083 0.0546875  0.07552083]
 [0.40234375 0.32421875 0.05371094 0.09635417]
 [0.3251953

[[0.00878906 0.18783542 0.04101562 0.1019678 ]
 [0.078125   0.15384615 0.03613281 0.09838998]
 [0.109375   0.13416816 0.03125    0.07871199]
 [0.16503906 0.16994633 0.03417969 0.09123435]
 [0.18164062 0.28801431 0.03320312 0.08407871]
 [0.23339844 0.15742397 0.03417969 0.08944544]
 [0.28808594 0.15026834 0.03125    0.07155635]
 [0.265625   0.27191413 0.03417969 0.07871199]
 [0.37890625 0.09481216 0.03222656 0.07692308]
 [0.46972656 0.08765653 0.03417969 0.08586762]
 [0.5625     0.12701252 0.03125    0.07871199]
 [0.34570312 0.27012522 0.03417969 0.0822898 ]
 [0.42871094 0.25939177 0.03613281 0.08944544]
 [0.49902344 0.28264758 0.02832031 0.07334526]
 [0.54394531 0.25402504 0.03613281 0.08765653]
 [0.61914062 0.0411449  0.03320312 0.08944544]
 [0.63476562 0.18246869 0.03417969 0.08586762]
 [0.671875   0.09838998 0.03613281 0.08765653]
 [0.74707031 0.06797853 0.03417969 0.0822898 ]
 [0.7265625  0.17173524 0.03417969 0.08586762]
 [0.8203125  0.13953488 0.03613281 0.09481216]
 [0.84863281 

[[0.109375   0.16145833 0.04882812 0.1015625 ]
 [0.21777344 0.15755208 0.05273438 0.09765625]
 [0.32519531 0.15364583 0.05371094 0.09635417]
 [0.46386719 0.13802083 0.0546875  0.09765625]
 [0.57226562 0.16927083 0.04785156 0.09114583]
 [0.64648438 0.20442708 0.05371094 0.09375   ]
 [0.74121094 0.21744792 0.0546875  0.08072917]
 [0.79980469 0.26432292 0.05566406 0.09505208]]
[[0.34277344 0.02339181 0.29003906 0.20272904]]
[[0.22460938 0.18292683 0.078125   0.1195122 ]
 [0.62695312 0.17073171 0.07617188 0.1097561 ]]
[[0.17382812 0.17213115 0.07226562 0.1147541 ]
 [0.4296875  0.06830601 0.06054688 0.12021858]]
[[0.35742188 0.12643678 0.31542969 0.32386748]]
[[0.22949219 0.16968326 0.33886719 0.37254902]]
[[0.54003906 0.08972692 0.11425781 0.09362809]]
[[0.49121094 0.29118029 0.09082031 0.0920882 ]]
[[0.13378906 0.14605418 0.046875   0.0647821 ]
 [0.27636719 0.15194346 0.04785156 0.07067138]
 [0.453125   0.11660777 0.04492188 0.07184923]
 [0.61035156 0.07302709 0.04785156 0.06124853]
 [0.7

[[0.01464844 0.01777434 0.46386719 0.47449768]
 [0.4375     0.13910355 0.50878906 0.48299845]]
[[0.67773438 0.18055556 0.10351562 0.23611111]
 [0.27929688 0.06597222 0.12304688 0.26388889]]
[[0.46191406 0.4789098  0.15332031 0.15055159]
 [0.56738281 0.34198572 0.17089844 0.14471123]]
[[0.68945312 0.35416667 0.08789062 0.18229167]]
[[0.21484375 0.33456153 0.18945312 0.19749447]
 [0.51269531 0.15475313 0.23535156 0.23286662]]
[[0.38769531 0.16178624 0.20019531 0.20131772]]
[[0.4375     0.10677083 0.08984375 0.171875  ]]
[[0.41601562 0.16753927 0.21679688 0.51308901]]
[[0.13476562 0.296875   0.13085938 0.27604167]
 [0.49414062 0.32552083 0.11914062 0.2109375 ]
 [0.80859375 0.15885417 0.1484375  0.28645833]]
[[0.23046875 0.13134328 0.16992188 0.69850746]
 [0.78125    0.14328358 0.0625     0.25671642]]
[[0.41601562 0.17585302 0.28222656 0.25590551]]
[[0.375      0.22807018 0.26367188 0.25341131]]
[[0.09960938 0.15776241 0.59082031 0.50534255]]
[[0.58007812 0.41666667 0.17578125 0.45833333]]

[[0.62011719 0.32621748 0.21679688 0.18545697]
 [0.40527344 0.19146097 0.21386719 0.20280187]]
[[0.10546875 0.30952381 0.11132812 0.46428571]
 [0.63671875 0.10714286 0.13867188 0.66666667]]
[[0.41015625 0.1640625  0.19921875 0.1875    ]]
[[0.15234375 0.30990415 0.12304688 0.31948882]
 [0.45117188 0.12779553 0.1484375  0.40255591]
 [0.75195312 0.39297125 0.14257812 0.23961661]]
[[0.18164062 0.31625183 0.20507812 0.24597365]]
[[0.24316406 0.18720657 0.44433594 0.36678404]]
[[0.53125    0.05989583 0.34765625 0.55729167]]
[[0.54882812 0.3531746  0.11132812 0.25793651]]
[[0.44042969 0.31167934 0.14355469 0.14789219]]
[[0.51171875 0.22315202 0.16796875 0.32914923]]
[[0.47070312 0.28877005 0.15039062 0.26470588]]
[[0.63476562 0.09077599 0.10546875 0.23426061]
 [0.43945312 0.10541728 0.1015625  0.19619327]]
[[0.24023438 0.14415675 0.34082031 0.34919524]]
[[0.24414062 0.28617886 0.12109375 0.27317073]
 [0.484375   0.1495935  0.14257812 0.39349593]]
[[0.31738281 0.16551724 0.43359375 0.45655172]

[[0.859375   0.18740849 0.125      0.19106881]
 [0.06738281 0.21888726 0.19238281 0.20497804]]
[[0.46484375 0.16983895 0.18359375 0.39824305]]
[[0.46875    0.05856515 0.1171875  0.13469985]]
[[0.203125   0.21879383 0.11523438 0.22440393]]
[[0.47851562 0.31770045 0.23828125 0.51134644]]
[[0.34277344 0.06430446 0.23828125 0.23818898]]
[[0.36328125 0.0034965  0.41601562 0.94405594]]
[[0.41894531 0.13836066 0.21191406 0.20721311]]
[[0.10742188 0.18088737 0.25585938 0.54266212]
 [0.49609375 0.4334471  0.2578125  0.51877133]]
[[0.01367188 0.1863354  0.16601562 0.77846791]
 [0.26171875 0.16977226 0.18554688 0.79503106]
 [0.515625   0.14906832 0.1484375  0.8115942 ]]
[[0.41015625 0.29662635 0.2421875  0.23806493]]
[[0.171875   0.01748252 0.38085938 0.75524476]]
[[0.54296875 0.128      0.18164062 0.512     ]]
[[0.32910156 0.19720187 0.0859375  0.0739507 ]]
[[0.44433594 0.14285714 0.24414062 0.25454545]]
[[0.12304688 0.63194444 0.06445312 0.19791667]
 [0.2734375  0.80902778 0.0625     0.18055556

[[0.3828125  0.20087719 0.2890625  0.36929825]]
[[0.31835938 0.14410188 0.34375    0.3116622 ]]
[[0.40039062 0.07782101 0.10839844 0.11348898]]
[[0.38964844 0.10338101 0.19921875 0.18335501]]
[[0.42773438 0.07409836 0.19140625 0.18360656]]
[[0.35742188 0.17323481 0.27148438 0.29885057]]
[[0.34277344 0.09774436 0.23339844 0.26992481]]
[[0.41210938 0.0920882  0.1796875  0.15629053]]
[[0.27539062 0.21470588 0.0859375  0.17058824]
 [0.48046875 0.37647059 0.09570312 0.15588235]
 [0.64257812 0.03235294 0.10351562 0.23529412]
 [0.87890625 0.01176471 0.11523438 0.2       ]]
[[0.3984375  0.1021021  0.15234375 0.33033033]]
[[0.29492188 0.17971014 0.17089844 0.18768116]]
[[0.34765625 0.12884334 0.22265625 0.44216691]]
[[0.38671875 0.14619883 0.29882812 0.26900585]]
[[0.29589844 0.08565737 0.359375   0.33399734]]
[[0.54296875 0.07662835 0.19921875 0.38825032]
 [0.24414062 0.10217114 0.1796875  0.33716475]]
[[0.31933594 0.11924686 0.43945312 0.45048815]]
[[0.296875   0.3125     0.16210938 0.3046875

[[0.0546875  0.40731707 0.078125   0.12682927]
 [0.31054688 0.25365854 0.09570312 0.10731707]
 [0.59570312 0.21219512 0.07617188 0.12195122]
 [0.79492188 0.28292683 0.09179688 0.1195122 ]
 [0.81640625 0.51707317 0.06445312 0.14146341]]
[[0.578125   0.23612751 0.08789062 0.1322314 ]]
[[0.33789062 0.25520833 0.06445312 0.125     ]
 [0.51757812 0.23177083 0.0703125  0.12239583]
 [0.71484375 0.26041667 0.0703125  0.125     ]]
[[0.43359375 0.14934114 0.14453125 0.26354319]]
[[0.49804688 0.09163592 0.10839844 0.11500615]]
[[0.40039062 0.16927083 0.26855469 0.20442708]]
[[0.4296875  0.05301915 0.07421875 0.13843888]
 [0.57226562 0.05891016 0.08007812 0.14138439]]
[[0.17773438 0.25256975 0.07226562 0.12628488]
 [0.328125   0.23788546 0.06445312 0.13215859]
 [0.43554688 0.28193833 0.078125   0.13803231]
 [0.58398438 0.32011747 0.07421875 0.12628488]
 [0.71875    0.23788546 0.07226562 0.13215859]]
[[0.21875    0.15972222 0.06054688 0.0787037 ]
 [0.68945312 0.22453704 0.05273438 0.07407407]]
[[0.

[[0.3515625  0.29095675 0.22949219 0.21035387]]
[[0.3359375  0.1485342  0.2109375  0.21042345]]
[[0.41503906 0.04123077 0.13964844 0.11692308]]
[[0.27929688 0.21646144 0.40917969 0.39209332]]
[[0.20703125 0.24805103 0.19921875 0.21261517]]
[[0.43164062 0.171875   0.1875     0.29947917]]
[[0.44140625 0.23703704 0.08007812 0.1362963 ]]
[[0.4765625  0.26302083 0.19140625 0.36458333]]
[[0.1953125  0.13046701 0.49316406 0.49147517]]
[[0.35839844 0.20105471 0.15625    0.13052076]]
[[0.82910156 0.28550512 0.02832031 0.06002928]
 [0.79785156 0.38945827 0.02734375 0.06734993]
 [0.74511719 0.31771596 0.02832031 0.06002928]
 [0.72265625 0.23279649 0.03027344 0.0556369 ]
 [0.71191406 0.1727672  0.02539062 0.05710102]
 [0.73144531 0.44216691 0.03027344 0.06881406]
 [0.67480469 0.37628111 0.02734375 0.06149341]
 [0.6796875  0.28696925 0.03027344 0.06442167]
 [0.62695312 0.25329429 0.02734375 0.06002928]
 [0.64648438 0.19912152 0.02539062 0.05124451]
 [0.609375   0.31039531 0.02734375 0.05710102]
 [0

[[0.3359375  0.12884334 0.140625   0.12518302]
 [0.59375    0.17203514 0.1328125  0.12884334]]
[[0.42773438 0.30746706 0.23632812 0.5124451 ]
 [0.203125   0.04099561 0.27148438 0.63836018]]
[[0.19628906 0.21052632 0.04199219 0.0994152 ]
 [0.74414062 0.14181287 0.05078125 0.12280702]]
[[0.70117188 0.0387931  0.12402344 0.14482759]
 [0.56445312 0.11551724 0.11035156 0.14827586]]
[[0.1171875  0.37603306 0.24804688 0.42355372]
 [0.37109375 0.29132231 0.31640625 0.34504132]]
[[0.12597656 0.29837134 0.30957031 0.23583062]
 [0.28320312 0.05081433 0.35644531 0.27296417]]
[[0.23828125 0.1640625  0.28710938 0.44791667]
 [0.60742188 0.38802083 0.27929688 0.48697917]]
[[0.52148438 0.22916667 0.31054688 0.57291667]
 [0.26367188 0.01302083 0.35351562 0.55729167]]
[[0.36230469 0.04892368 0.09667969 0.10176125]
 [0.51757812 0.07632094 0.09667969 0.09197652]]
[[0.375      0.11906311 0.12011719 0.10149642]
 [0.56933594 0.17761874 0.10839844 0.08783344]]
[[0.34277344 0.14756944 0.02929688 0.09201389]
 [0

[[0.10351562 0.33390119 0.09179688 0.2044293 ]]
[[0.30664062 0.17278618 0.55664062 0.71706263]]
[[0.81054688 0.16933333 0.08007812 0.188     ]
 [0.61328125 0.23333333 0.05175781 0.10933333]
 [0.37109375 0.32133333 0.09667969 0.172     ]
 [0.22558594 0.33066667 0.046875   0.17866667]]
[[0.11523438 0.31648936 0.04980469 0.06781915]
 [0.21191406 0.31648936 0.05371094 0.06515957]
 [0.21582031 0.46276596 0.04199219 0.07047872]
 [0.30175781 0.31117021 0.05175781 0.0731383 ]
 [0.40625    0.31382979 0.05175781 0.06914894]
 [0.45996094 0.4375     0.04394531 0.09308511]
 [0.51171875 0.32180851 0.05175781 0.06648936]
 [0.61035156 0.31515957 0.05273438 0.06648936]
 [0.85058594 0.00398936 0.05371094 0.06382979]
 [0.8515625  0.13829787 0.05664062 0.06914894]
 [0.71777344 0.32845745 0.05371094 0.06781915]
 [0.81542969 0.32712766 0.05566406 0.06914894]
 [0.91015625 0.32180851 0.05273438 0.07047872]]
[[0.13476562 0.06934813 0.05664062 0.10263523]
 [0.49804688 0.04715673 0.05664062 0.11373093]]
[[0.3554

[[0.16796875 0.19648094 0.09960938 0.2111437 ]
 [0.37304688 0.20821114 0.08984375 0.19648094]
 [0.58789062 0.15835777 0.09375    0.19354839]
 [0.73046875 0.20821114 0.09960938 0.16715543]
 [0.25       0.51612903 0.11328125 0.20821114]
 [0.47460938 0.46041056 0.11132812 0.25806452]
 [0.67773438 0.53372434 0.09570312 0.20821114]]
[[0.54980469 0.14252874 0.15136719 0.18314176]
 [0.20605469 0.33793103 0.15625    0.1440613 ]]
[[0.50976562 0.26527678 0.31347656 0.30841121]]
[[0.15625    0.26939971 0.07617188 0.15812592]
 [0.32617188 0.19033675 0.07226562 0.16398243]
 [0.48632812 0.27525622 0.0625     0.14348463]
 [0.58398438 0.12884334 0.0859375  0.16105417]
 [0.73632812 0.12005857 0.09375    0.18740849]]
[[0.15234375 0.28328612 0.08203125 0.14164306]
 [0.3671875  0.31161473 0.07421875 0.14730878]
 [0.54882812 0.47592068 0.08203125 0.13597734]
 [0.32226562 0.65155807 0.06640625 0.12464589]
 [0.19140625 0.11331445 0.08007812 0.13314448]
 [0.32617188 0.16713881 0.07421875 0.15580737]
 [0.47851

[[0.56640625 0.1317716  0.08984375 0.18448023]
 [0.69726562 0.26647145 0.1015625  0.21376281]]
[[0.03710938 0.19932432 0.16015625 0.37837838]
 [0.22851562 0.59121622 0.1640625  0.38175676]
 [0.37304688 0.23986486 0.16015625 0.34459459]
 [0.5546875  0.39864865 0.17382812 0.40202703]
 [0.72851562 0.02364865 0.18359375 0.34121622]]
[[0.21289062 0.27915633 0.04785156 0.0719603 ]
 [0.390625   0.29776675 0.04785156 0.07816377]
 [0.546875   0.23076923 0.04882812 0.0707196 ]
 [0.70703125 0.21215881 0.04980469 0.07816377]
 [0.58300781 0.47022333 0.04785156 0.06947891]
 [0.4296875  0.49875931 0.046875   0.06327543]
 [0.21972656 0.49255583 0.06054688 0.06823821]]
[[0.21679688 0.30503979 0.18164062 0.22281167]
 [0.375      0.50928382 0.15234375 0.23607427]
 [0.60351562 0.19628647 0.16796875 0.27851459]
 [0.62890625 0.63395225 0.16210938 0.22015915]]
[[0.1328125  0.25260417 0.04003906 0.06119792]
 [0.21875    0.26041667 0.03613281 0.05598958]
 [0.27539062 0.25       0.03808594 0.05729167]
 [0.36718

[[0.19140625 0.05771144 0.48632812 0.74427861]]
[[0.22070312 0.04166667 0.07421875 0.14322917]
 [0.71679688 0.09114583 0.06445312 0.10416667]]
[[0.6796875  0.27387802 0.05078125 0.09436133]]
[[0.63085938 0.13157895 0.1875     0.28070175]]
[[0.57421875 0.09040794 0.0625     0.1014333 ]
 [0.81835938 0.07717751 0.06054688 0.09261301]
 [0.34570312 0.07056229 0.07226562 0.09702315]
 [0.10546875 0.08820287 0.06640625 0.08599779]]
[[0.08984375 0.05769231 0.10351562 0.18269231]
 [0.58984375 0.0625     0.10351562 0.17548077]
 [0.59375    0.56971154 0.1015625  0.18028846]
 [0.08984375 0.57932692 0.1015625  0.17067308]
 [0.44140625 0.54086538 0.05664062 0.19230769]]
[[0.30957031 0.16938111 0.546875   0.52638436]]
[[0.54296875 0.17836257 0.19726562 0.19883041]
 [0.1953125  0.35964912 0.27734375 0.25146199]]
[[0.55859375 0.128      0.24023438 0.324     ]]
[[0.25195312 0.20319303 0.44335938 0.44847605]]
[[0.29296875 0.18542615 0.22851562 0.18737801]
 [0.42480469 0.09759271 0.16113281 0.13272609]]
[[

[[0.43359375 0.35540984 0.17480469 0.15213115]]
[[0.61425781 0.11341632 0.11035156 0.08990318]
 [0.33300781 0.12863071 0.10742188 0.09543568]]
[[0.33984375 0.19497908 0.2890625  0.38493724]]
[[0.36914062 0.2540913  0.28320312 0.24375538]]
[[0.57226562 0.1484375  0.11132812 0.11914062]
 [0.3046875  0.15625    0.14941406 0.13867188]]
[[0.41308594 0.34992679 0.03515625 0.07027818]
 [0.49023438 0.27964861 0.03417969 0.07467057]
 [0.56445312 0.33089312 0.03222656 0.06881406]]
[[0.64746094 0.16601816 0.09960938 0.08819715]
 [0.33203125 0.08171206 0.10253906 0.09792477]]
[[0.31933594 0.1461039  0.3515625  0.28051948]]
[[0.44726562 0.18807947 0.1484375  0.19602649]
 [0.64257812 0.14834437 0.11914062 0.19337748]]
[[0.31640625 0.51732523 0.09375    0.08571429]
 [0.5234375  0.07598784 0.11914062 0.07598784]]
[[0.40234375 0.10159363 0.16992188 0.13678619]]
[[0.46289062 0.25976562 0.08203125 0.06445312]]
[[0.65234375 0.1037037  0.12988281 0.1308642 ]
 [0.27539062 0.13497942 0.09765625 0.12098765]
 

[[0.14257812 0.09114583 0.0625     0.13020833]
 [0.58984375 0.09895833 0.08789062 0.15364583]
 [0.69335938 0.171875   0.10742188 0.1796875 ]]
[[0.37207031 0.16157205 0.21972656 0.18340611]]
[[0.54492188 0.1599064  0.10253906 0.11700468]]
[[0.67382812 0.11238825 0.09765625 0.13282248]]
[[0.12304688 0.1626575  0.13867188 0.26804124]
 [0.4453125  0.26345934 0.12890625 0.19931271]
 [0.6953125  0.20847652 0.13867188 0.21993127]]
[[0.52539062 0.23138298 0.07617188 0.13829787]]
[[0.23925781 0.16197183 0.36328125 0.34194053]]
[[0.4765625  0.40659341 0.109375   0.11355311]]
[[0.60351562 0.15249267 0.17382812 0.29618768]]
[[0.375      0.24778761 0.25292969 0.24557522]]
[[0.42382812 0.26315789 0.06640625 0.13622291]]
[[0.3828125  0.25934066 0.09375    0.3032967 ]]
[[0.17871094 0.16575875 0.45117188 0.49805447]]
[[0.78320312 0.37695312 0.12109375 0.15625   ]]
[[0.56640625 0.09179688 0.09375    0.08984375]]
[[0.3984375  0.26041667 0.0625     0.17361111]]
[[0.36132812 0.2425     0.15234375 0.2625   

[[0.38085938 0.17992177 0.33789062 0.35202086]]
[[0.34570312 0.2079063  0.55078125 0.50951684]]
[[0.15234375 0.18950437 0.3046875  0.25655977]]
[[0.42578125 0.2109375  0.2421875  0.3046875 ]]
[[0.15820312 0.3671072  0.16015625 0.2143906 ]
 [0.58007812 0.41409692 0.12109375 0.27606461]]
[[0.64648438 0.11368421 0.09765625 0.31157895]]
[[0.54101562 0.33491311 0.19140625 0.17693523]]
[[0.40625    0.21679688 0.19140625 0.27539062]]
[[0.55273438 0.67382812 0.16210938 0.09375   ]
 [0.2421875  0.6171875  0.05859375 0.05859375]]
[[0.26074219 0.62174479 0.48339844 0.34049479]]
[[0.23730469 0.33995585 0.02832031 0.10375276]]
[[0.70117188 0.72301691 0.22851562 0.20286086]]
[[0.48242188 0.44865719 0.23046875 0.3507109 ]]
[[0.45507812 0.2265625  0.22265625 0.2890625 ]]
[[0.3671875  0.55929722 0.06445312 0.0966325 ]
 [0.26953125 0.18740849 0.0703125  0.08784773]]
[[0.47070312 0.18945312 0.23828125 0.29882812]]
[[0.19140625 0.19619327 0.32421875 0.25183016]]
[[0.58007812 0.33557047 0.1875     0.432885

[[0.31640625 0.52686308 0.1015625  0.24263432]
 [0.41992188 0.17677643 0.12109375 0.27383016]]
[[0.51660156 0.12308998 0.08984375 0.09932088]
 [0.01367188 0.34210526 0.06542969 0.07640068]]
[[0.51855469 0.28119063 0.2890625  0.11716276]]
[[0.44921875 0.33941094 0.17773438 0.27769986]]
[[0.22851562 0.3326226  0.18359375 0.58848614]]
[[0.38378906 0.1800379  0.24804688 0.22299431]]
[[0.25390625 0.12516297 0.22851562 0.35462842]
 [0.57617188 0.35202086 0.19140625 0.31029987]]
[[0.22949219 0.16022099 0.3046875  0.35122336]]
[[0.62695312 0.25806452 0.125      0.19648094]]
[[0.23046875 0.40625    0.27148438 0.375     ]
 [0.49023438 0.2421875  0.25195312 0.41145833]]
[[0.328125   0.57808219 0.16308594 0.22100457]
 [0.55957031 0.56621005 0.28808594 0.13242009]
 [0.61621094 0.21643836 0.14453125 0.20091324]
 [0.13964844 0.33789954 0.26269531 0.15068493]]
[[0.27734375 0.21679688 0.46875    0.71484375]]
[[0.51757812 0.10541728 0.09570312 0.17569546]]
[[0.21679688 0.45387994 0.05957031 0.11566618]


[[0.09375    0.26041667 0.08984375 0.16666667]
 [0.25585938 0.16927083 0.11328125 0.18229167]
 [0.5390625  0.15104167 0.09765625 0.1640625 ]
 [0.83984375 0.08333333 0.10546875 0.1953125 ]]
[[0.13671875 0.28117359 0.09375    0.19315403]
 [0.35742188 0.23471883 0.09570312 0.16625917]
 [0.5546875  0.18337408 0.11328125 0.2200489 ]
 [0.78320312 0.20782396 0.11328125 0.1809291 ]]
[[0.265625   0.20550459 0.07421875 0.21284404]]
[[0.12109375 0.09103841 0.10546875 0.17923186]
 [0.4609375  0.17354196 0.11132812 0.17638691]
 [0.77929688 0.09672831 0.08203125 0.18207681]]
[[0.39453125 0.14619883 0.15234375 0.25730994]
 [0.01757812 0.44444444 0.15625    0.23976608]]
[[0.08886719 0.00770713 0.64941406 0.44123314]]
[[0.04882812 0.12110727 0.1875     0.48788927]
 [0.37890625 0.0899654  0.18554688 0.49480969]
 [0.74414062 0.15224913 0.2109375  0.44982699]]
[[0.22070312 0.134375   0.05273438 0.121875  ]
 [0.38867188 0.159375   0.06835938 0.134375  ]
 [0.51953125 0.175      0.0625     0.13125   ]
 [0.67

[[0.30566406 0.12125341 0.38964844 0.40054496]]
[[0.01269531 0.03526221 0.7109375  0.79927667]]
[[0.38476562 0.10763889 0.12890625 0.28472222]]
[[0.34765625 0.09635417 0.08789062 0.171875  ]]
[[0.21679688 0.12152778 0.22851562 0.60763889]]
[[0.25585938 0.21073171 0.46484375 0.61658537]]
[[0.4921875  0.12772134 0.18359375 0.35994194]]
[[0.42382812 0.09570312 0.1328125  0.15039062]]
[[0.37695312 0.09025974 0.25292969 0.25064935]]
[[0.41308594 0.00759013 0.23144531 0.18532574]]
[[0.72460938 0.49090909 0.11328125 0.18636364]
 [0.25585938 0.04772727 0.10351562 0.28181818]]
[[0.53320312 0.11738484 0.15429688 0.14041605]
 [0.06933594 0.4717682  0.15917969 0.16567608]]
[[0.31738281 0.20714286 0.17089844 0.16233766]]
[[0.42578125 0.16666667 0.109375   0.140625  ]
 [0.5703125  0.03645833 0.09765625 0.171875  ]
 [0.14648438 0.5625     0.09570312 0.15885417]]
[[0.73925781 0.1579974  0.10546875 0.10143043]
 [0.25195312 0.15214564 0.10253906 0.13263979]]
[[0.29785156 0.07632094 0.2890625  0.29484671

[[0.67480469 0.08571429 0.08886719 0.1       ]
 [0.36035156 0.06466165 0.09863281 0.1037594 ]]
[[0.38378906 0.0625     0.19335938 0.16796875]]
[[0.63476562 0.14667536 0.23730469 0.19687093]
 [0.39746094 0.07627119 0.21972656 0.21056063]]
[[0.46484375 0.07617188 0.10546875 0.13476562]]
[[0.32519531 0.25976562 0.13183594 0.11328125]
 [0.74804688 0.03320312 0.17871094 0.15625   ]
 [0.02636719 0.46940104 0.08496094 0.1328125 ]]
[[0.3046875  0.12304688 0.12695312 0.171875  ]
 [0.51757812 0.08984375 0.09960938 0.18359375]]
[[0.34179688 0.13839286 0.13476562 0.17857143]
 [0.64648438 0.00446429 0.13671875 0.14732143]]
[[0.4921875  0.12896254 0.28027344 0.26945245]]
[[0.26757812 0.27539062 0.13085938 0.14257812]
 [0.59765625 0.11132812 0.14648438 0.16992188]]
[[0.08789062 0.10758377 0.37988281 0.3127572 ]]
[[0.67285156 0.37563822 0.13378906 0.10357403]]
[[0.38378906 0.21484375 0.3984375  0.35416667]]
[[0.203125   0.05078125 0.1171875  0.16601562]
 [0.69335938 0.06445312 0.1328125  0.1875    ]]


[[0.76757812 0.05610098 0.14453125 0.23562412]]
[[0.26757812 0.1143617  0.09960938 0.17287234]]
[[0.37402344 0.50945858 0.15820312 0.13502935]]
[[0.25683594 0.09967427 0.18164062 0.15635179]]
[[0.52636719 0.0998703  0.09667969 0.0998703 ]]
[[0.6484375  0.09978308 0.1640625  0.24078091]]
[[0.56640625 0.2381254  0.18066406 0.16402787]]
[[0.27148438 0.25346784 0.20800781 0.19924338]]
[[0.53710938 0.33798883 0.06054688 0.12011173]]
[[0.59765625 0.35620438 0.08007812 0.15182482]]
[[0.21679688 0.18125    0.56054688 0.67734375]]
[[0.31640625 0.24739583 0.16015625 0.296875  ]]
[[0.66015625 0.16733068 0.07226562 0.16201859]]
[[0.62695312 0.09370425 0.11132812 0.21083455]]
[[0.44140625 0.09791123 0.12011719 0.10182768]]
[[0.37695312 0.40831869 0.04980469 0.04276508]]
[[0.3515625  0.15053763 0.2734375  0.42580645]]
[[0.50976562 0.06060606 0.08203125 0.10909091]]
[[0.57421875 0.215625   0.07226562 0.140625  ]]
[[0.26757812 0.28111274 0.03027344 0.06002928]]
[[0.50976562 0.14040329 0.09667969 0.095

[[0.66699219 0.37056604 0.12890625 0.08226415]
 [0.04785156 0.5290566  0.13671875 0.07396226]]
[[0.43847656 0.37472119 0.09960938 0.08624535]]
[[0.66113281 0.19255456 0.05273438 0.10911425]
 [0.3984375  0.10654685 0.07910156 0.10269576]
 [0.50683594 0.75224647 0.0390625  0.08985879]
 [0.91308594 0.78818999 0.03613281 0.10012837]]
[[0.56347656 0.07992203 0.1640625  0.13840156]
 [0.31640625 0.388564   0.15820312 0.12475634]]
[[0.28320312 0.11718062 0.30566406 0.37268722]]
[[0.80859375 0.296875   0.03515625 0.06640625]
 [0.66894531 0.39713542 0.03613281 0.06640625]
 [0.46679688 0.31119792 0.03515625 0.04557292]
 [0.36621094 0.36588542 0.03125    0.05208333]
 [0.18847656 0.2890625  0.03710938 0.05598958]]
[[0.41992188 0.2133426  0.54394531 0.59207783]
 [0.11230469 0.09589993 0.52441406 0.61362057]]
[[0.28320312 0.2        0.09570312 0.17922078]
 [0.26757812 0.01298701 0.07226562 0.17402597]
 [0.8203125  0.2987013  0.06640625 0.14805195]]
[[0.33300781 0.24615385 0.12792969 0.14652015]
 [0.5

[[0.70703125 0.25585938 0.07910156 0.07421875]
 [0.21679688 0.265625   0.08203125 0.0859375 ]]
[[0.09765625 0.18104496 0.04589844 0.07411908]
 [0.10449219 0.38274605 0.04589844 0.07776428]
 [0.32324219 0.58687728 0.05273438 0.08383961]
 [0.32421875 0.36087485 0.04394531 0.07776428]
 [0.28027344 0.16524909 0.04394531 0.07533414]
 [0.43945312 0.14337789 0.04394531 0.07533414]
 [0.58886719 0.14823815 0.04199219 0.07533414]
 [0.54980469 0.36573512 0.04101562 0.07897934]
 [0.54003906 0.55407047 0.04785156 0.09234508]
 [0.73339844 0.36208991 0.04394531 0.08019441]
 [0.7578125  0.15309842 0.04589844 0.08383961]]
[[0.28125    0.10780142 0.1953125  0.4822695 ]
 [0.47070312 0.19858156 0.2421875  0.43971631]]
[[0.3046875  0.37643678 0.05566406 0.05100575]]
[[0.39550781 0.28246753 0.10839844 0.06233766]]
[[0.3671875  0.0412675  0.19921875 0.22033898]]
[[0.27539062 0.08731241 0.08007812 0.16098226]
 [0.640625   0.09822647 0.0859375  0.16371078]]
[[0.203125   0.08235294 0.58984375 0.82352941]]
[[0.2

[[0.55859375 0.11830986 0.12304688 0.24507042]
 [0.77539062 0.35211268 0.16210938 0.25633803]]
[[0.22460938 0.04227642 0.12695312 0.31219512]
 [0.68164062 0.23414634 0.1328125  0.30243902]]
[[0.4609375  0.12298682 0.08398438 0.16691069]
 [0.6640625  0.18155198 0.0546875  0.0966325 ]
 [0.3046875  0.21376281 0.07617188 0.16691069]
 [0.90234375 0.06442167 0.078125   0.16105417]]
[[0.31738281 0.39238653 0.04101562 0.0966325 ]
 [0.52929688 0.30161054 0.04003906 0.09956076]
 [0.7109375  0.16105417 0.03515625 0.06295754]]
[[0.42773438 0.04101562 0.12597656 0.11328125]]
[[0.3515625  0.10266535 0.11914062 0.15992103]]
[[0.32910156 0.0979342  0.09472656 0.0979342 ]
 [0.52832031 0.11706197 0.08691406 0.10328998]]
[[0.5390625  0.05555556 0.078125   0.17708333]]
[[0.59277344 0.49088542 0.31640625 0.11914062]
 [0.09375    0.55729167 0.26953125 0.12109375]]
[[0.44140625 0.09391192 0.28808594 0.2869171 ]]
[[0.32421875 0.14243323 0.39550781 0.46068249]]
[[0.421875   0.33403361 0.15234375 0.1407563 ]]
[

[[0.3125     0.13469985 0.08300781 0.07833089]
 [0.47167969 0.17789165 0.0859375  0.06442167]]
[[0.59277344 0.27951389 0.03222656 0.07638889]]
[[0.07519531 0.13541667 0.04980469 0.10026042]
 [0.1796875  0.11067708 0.046875   0.0859375 ]
 [0.22265625 0.38411458 0.04882812 0.08333333]
 [0.39160156 0.10026042 0.04882812 0.08723958]
 [0.37402344 0.34114583 0.05078125 0.09375   ]
 [0.52050781 0.32421875 0.05078125 0.09635417]
 [0.57226562 0.07161458 0.04882812 0.08854167]
 [0.72753906 0.07552083 0.05078125 0.08854167]
 [0.83105469 0.05338542 0.05078125 0.09244792]
 [0.85546875 0.32161458 0.05175781 0.09635417]
 [0.70703125 0.33333333 0.05175781 0.09375   ]]
[[0.46484375 0.3359375  0.05273438 0.0703125 ]]
[[0.12402344 0.22017045 0.04492188 0.07954545]
 [0.30761719 0.13920455 0.04589844 0.09232955]
 [0.61132812 0.35227273 0.04785156 0.09375   ]
 [0.78320312 0.22727273 0.04101562 0.09517045]
 [0.87695312 0.20170455 0.04394531 0.08948864]]
[[0.31054688 0.22712934 0.078125   0.12618297]
 [0.6328

[[0.74316406 0.16772554 0.05078125 0.09911055]]
[[0.43359375 0.09114583 0.22460938 0.44010417]]
[[0.59863281 0.18985696 0.04589844 0.08712614]]
[[0.25       0.2369281  0.04980469 0.10784314]
 [0.48144531 0.10294118 0.04980469 0.10947712]]
[[0.42578125 0.07976366 0.0625     0.12998523]]
[[0.36816406 0.06015625 0.10742188 0.11328125]
 [0.55078125 0.18125    0.10449219 0.09921875]]
[[0.17089844 0.353125   0.03613281 0.0921875 ]]
[[0.79296875 0.70052083 0.09375    0.09114583]
 [0.7421875  0.17447917 0.07617188 0.08333333]
 [0.74414062 0.65885417 0.1015625  0.0703125 ]]
[[0.3828125  0.26302083 0.07421875 0.171875  ]]
[[0.140625   0.02604167 0.046875   0.10590278]
 [0.1328125  0.12326389 0.04492188 0.109375  ]
 [0.24707031 0.16319444 0.04785156 0.12152778]
 [0.28125    0.03472222 0.04296875 0.10590278]
 [0.43945312 0.18055556 0.04589844 0.109375  ]
 [0.38476562 0.05381944 0.04101562 0.09548611]
 [0.51464844 0.03993056 0.04003906 0.10069444]
 [0.74804688 0.16145833 0.046875   0.10763889]
 [0.

[[0.23730469 0.15625    0.56347656 0.45182292]]
[[0.6640625  0.12071331 0.1171875  0.21124829]]
[[0.55859375 0.16666667 0.09375    0.19298246]]
[[0.52832031 0.14285714 0.125      0.12087912]]
[[0.65820312 0.22993197 0.08691406 0.14081633]]
[[0.31445312 0.30456853 0.078125   0.12944162]
 [0.51757812 0.14974619 0.06835938 0.1142132 ]]
[[0.39746094 0.06068966 0.10253906 0.11103448]
 [0.71582031 0.09724138 0.08007812 0.09586207]]
[[0.46289062 0.13636364 0.09375    0.08571429]]
[[0.26953125 0.25438596 0.10546875 0.17251462]]
[[0.40234375 0.234375   0.05273438 0.08333333]]
[[0.3046875  0.09342105 0.11035156 0.09210526]
 [0.61132812 0.09210526 0.09863281 0.09539474]]
[[0.58398438 0.1785174  0.05273438 0.11800303]]
[[0.39941406 0.13273002 0.078125   0.08597285]
 [0.234375   0.38838612 0.07324219 0.06862745]]
[[0.45898438 0.25844347 0.20898438 0.4082232 ]]
[[0.46484375 0.18485237 0.09179688 0.14377407]]
[[0.58496094 0.14248705 0.12011719 0.09585492]]
[[0.4921875  0.15316315 0.07421875 0.1109877

[[0.34570312 0.21484375 0.22265625 0.27539062]]
[[0.35351562 0.18039216 0.484375   0.7254902 ]]
[[0.31640625 0.54166667 0.07421875 0.09375   ]]
[[0.58398438 0.16988131 0.11035156 0.13278932]
 [0.76855469 0.22626113 0.11035156 0.13278932]]
[[0.42675781 0.10168394 0.1796875  0.18717617]]
[[0.39648438 0.3671875  0.22070312 0.29166667]]
[[0.21191406 0.06272794 0.0859375  0.11670314]
 [0.63183594 0.15390226 0.08886719 0.08388038]]
[[0.44238281 0.1444522  0.19628906 0.15003489]]
[[0.43066406 0.1467803  0.19726562 0.29261364]]
[[0.43945312 0.19791667 0.06640625 0.12152778]
 [0.2578125  0.09375    0.09375    0.17708333]]
[[0.0859375  0.109375   0.1640625  0.234375  ]
 [0.06640625 0.63541667 0.16210938 0.27604167]
 [0.1796875  0.59635417 0.16601562 0.24739583]
 [0.62304688 0.61458333 0.12695312 0.27604167]
 [0.74609375 0.6015625  0.14648438 0.22916667]
 [0.35351562 0.04166667 0.14648438 0.265625  ]
 [0.53710938 0.12239583 0.1484375  0.24739583]
 [0.70898438 0.22916667 0.14648438 0.20052083]]
[[

[[0.39648438 0.39215686 0.08789062 0.15455594]]
[[0.6015625  0.4712813  0.05664062 0.07069219]]
[[0.12304688 0.14644351 0.07519531 0.09372385]
 [0.28515625 0.2209205  0.06640625 0.08033473]
 [0.6015625  0.08953975 0.06640625 0.08786611]
 [0.78613281 0.10962343 0.0703125  0.08200837]
 [0.46484375 0.31631799 0.06835938 0.08786611]
 [0.62890625 0.25188285 0.07519531 0.08953975]
 [0.796875   0.25020921 0.0703125  0.08200837]
 [0.24121094 0.47447699 0.07519531 0.09205021]
 [0.42578125 0.45271967 0.08007812 0.09205021]
 [0.65136719 0.51715481 0.08203125 0.09790795]]
[[0.32617188 0.22254758 0.06445312 0.1522694 ]]
[[0.23046875 0.06485084 0.07226562 0.11932555]
 [0.39453125 0.08560311 0.0703125  0.12191958]
 [0.578125   0.07263294 0.0625     0.11673152]
 [0.74804688 0.05188067 0.06640625 0.09857328]
 [0.41015625 0.50324254 0.08984375 0.12191958]
 [0.5390625  0.52140078 0.07226562 0.12970169]]
[[0.25390625 0.2265625  0.07617188 0.1484375 ]
 [0.43554688 0.2578125  0.0703125  0.13802083]
 [0.5605

[[0.60546875 0.54528031 0.12792969 0.07810254]]
[[0.43457031 0.1328125  0.14648438 0.140625  ]]
[[0.18066406 0.29166667 0.03027344 0.04296875]
 [0.27929688 0.29166667 0.02734375 0.04166667]
 [0.36425781 0.26822917 0.03027344 0.04166667]
 [0.44824219 0.24739583 0.03027344 0.05208333]
 [0.5390625  0.21875    0.03125    0.04166667]
 [0.68261719 0.18359375 0.03125    0.04947917]
 [0.74609375 0.19921875 0.03125    0.046875  ]
 [0.77832031 0.24348958 0.03417969 0.04817708]
 [0.16210938 0.35546875 0.02734375 0.046875  ]
 [0.20996094 0.36067708 0.03027344 0.04036458]
 [0.29394531 0.35546875 0.02929688 0.046875  ]
 [0.34863281 0.36328125 0.02929688 0.04296875]
 [0.41210938 0.36328125 0.03125    0.05729167]
 [0.48828125 0.36067708 0.03222656 0.05078125]
 [0.54394531 0.37109375 0.02929688 0.04947917]
 [0.60449219 0.37890625 0.03125    0.04947917]
 [0.65722656 0.33072917 0.03320312 0.05598958]
 [0.73046875 0.359375   0.03027344 0.05078125]
 [0.06640625 0.51953125 0.03710938 0.05598958]
 [0.1669921

[[0.48828125 0.24560261 0.18457031 0.16416938]
 [0.20214844 0.67100977 0.23730469 0.22605863]]
[[0.67773438 0.384375   0.17382812 0.31875   ]]
[[0.40234375 0.02933333 0.21484375 0.41866667]]
[[0.37695312 0.12884334 0.2890625  0.54465593]]
[[0.47363281 0.11319681 0.25878906 0.24061433]]
[[0.41992188 0.17862372 0.22851562 0.42459736]]
[[0.56835938 0.34490239 0.125      0.18004338]]
[[0.21289062 0.55294118 0.09375    0.24117647]
 [0.75195312 0.19411765 0.09570312 0.24411765]]
[[0.45703125 0.07963875 0.07421875 0.11904762]]
[[0.1796875  0.31164902 0.16015625 0.2934947 ]]
[[0.1484375  0.41520468 0.11914062 0.17251462]]
[[0.10351562 0.21268926 0.57714844 0.45710166]]
[[0.29785156 0.21642364 0.54589844 0.580967  ]]
[[0.40234375 0.18055556 0.18554688 0.39236111]]
[[0.51367188 0.30249633 0.1484375  0.26431718]]
[[0.3671875  0.26737968 0.20507812 0.28074866]]
[[0.43359375 0.50658858 0.12890625 0.21961933]]
[[0.30175781 0.1581002  0.08203125 0.08002602]
 [0.59570312 0.37931034 0.10546875 0.085881

[[0.25976562 0.1677763  0.35351562 0.52996005]]
[[0.44140625 0.27864583 0.20703125 0.34375   ]]
[[0.265625   0.20478723 0.25       0.39095745]]
[[0.40039062 0.29032258 0.20898438 0.37243402]]
[[0.39648438 0.19345455 0.22265625 0.18763636]]
[[0.40039062 0.09705373 0.19726562 0.43327556]]
[[0.37695312 0.27160494 0.234375   0.4005487 ]]
[[0.41015625 0.3250366  0.17382812 0.30161054]]
[[0.44726562 0.28094576 0.24609375 0.45618915]]
[[0.18554688 0.16983895 0.26171875 0.53879941]]
[[0.5234375  0.095953   0.10546875 0.09986945]
 [0.51464844 0.2578329  0.09375    0.08028721]]
[[0.328125   0.24652778 0.3515625  0.75347222]]
[[0.42382812 0.31625183 0.18164062 0.36896047]]
[[0.3828125  0.15773509 0.20898438 0.29524772]]
[[0.46679688 0.11320755 0.18164062 0.13836478]]
[[0.39453125 0.12776413 0.35546875 0.53808354]]
[[0.45898438 0.2826087  0.125      0.22981366]]
[[0.4296875  0.16612589 0.30859375 0.27774173]]
[[0.359375   0.47368421 0.25390625 0.33918129]]
[[0.68359375 0.15224913 0.13867188 0.2975

[[0.51757812 0.00693241 0.18164062 0.48873484]]
[[0.32226562 0.07279029 0.34960938 0.91161179]]
[[0.43945312 0.15084525 0.11328125 0.23407022]]
[[0.47265625 0.24235294 0.05078125 0.07529412]]
[[0.36230469 0.1463035  0.09765625 0.12684825]]
[[0.38769531 0.0796875  0.11914062 0.1265625 ]]
[[0.52636719 0.11143695 0.23144531 0.23460411]]
[[0.35644531 0.30510753 0.03417969 0.07930108]
 [0.38964844 0.29704301 0.04296875 0.08333333]]
[[0.58398438 0.25701625 0.05273438 0.10635155]
 [0.53125    0.23338257 0.05859375 0.12407681]
 [0.3671875  0.16543575 0.05273438 0.1211226 ]
 [0.19335938 0.20679468 0.05273438 0.11816839]]
[[0.84570312 0.15151515 0.04003906 0.07936508]
 [0.53613281 0.19480519 0.05078125 0.08369408]
 [0.30273438 0.15584416 0.03515625 0.06493506]
 [0.07910156 0.21645022 0.04199219 0.06204906]]
[[0.36914062 0.109375   0.07226562 0.14322917]
 [0.43945312 0.21875    0.0625     0.1484375 ]
 [0.55859375 0.08072917 0.10742188 0.18229167]]
[[0.58789062 0.16015625 0.03613281 0.08984375]]
[

[[0.29101562 0.16319444 0.15429688 0.36458333]
 [0.515625   0.11111111 0.1796875  0.44791667]]
[[0.49414062 0.17569546 0.23242188 0.43045388]]
[[0.4921875  0.125      0.07226562 0.10742188]]
[[0.6484375  0.13967311 0.10351562 0.17236256]]
[[0.29101562 0.21286174 0.45410156 0.40836013]]
[[0.65820312 0.34570312 0.07617188 0.10742188]]
[[0.54296875 0.15972222 0.0625     0.17361111]]
[[0.48242188 0.63678969 0.25390625 0.19156415]]
[[0.45410156 0.03155522 0.09667969 0.11495116]]
[[0.34179688 0.17398946 0.13671875 0.11130639]
 [0.3515625  0.32220269 0.12402344 0.076157  ]
 [0.61230469 0.12478032 0.14648438 0.10544815]
 [0.78222656 0.54891623 0.12011719 0.08787346]]
[[0.51660156 0.08192568 0.31835938 0.5464527 ]]
[[0.33203125 0.38020833 0.1171875  0.20052083]]
[[0.4765625  0.46920821 0.02246094 0.0483871 ]
 [0.37988281 0.49706745 0.02148438 0.03665689]
 [0.29003906 0.48240469 0.02636719 0.03958944]
 [0.24707031 0.47507331 0.03222656 0.0483871 ]]
[[0.33203125 0.18740849 0.11523438 0.25475842]]

[[0.37890625 0.15813424 0.12109375 0.07792947]]
[[0.36328125 0.08680556 0.33984375 0.84027778]]
[[0.30273438 0.12884334 0.0703125  0.1522694 ]]
[[0.41210938 0.03806228 0.10351562 0.23529412]]
[[0.53125    0.12144703 0.05273438 0.0749354 ]]
[[0.19824219 0.0247093  0.11621094 0.26598837]
 [0.72265625 0.30668605 0.07324219 0.13372093]
 [0.83496094 0.42877907 0.046875   0.10174419]
 [0.9140625  0.42151163 0.04101562 0.10174419]]
[[0.33886719 0.07243319 0.11425781 0.10759494]]
[[0.5234375  0.20647249 0.21191406 0.16569579]]
[[0.390625   0.1443299  0.19335938 0.42120766]]
[[0.421875   0.10541728 0.05273438 0.09956076]]
[[0.65039062 0.04894083 0.12792969 0.20891161]]
[[0.6953125  0.09342784 0.11523438 0.09729381]]
[[0.43847656 0.10530246 0.20703125 0.21657954]]
[[0.57226562 0.265625   0.0859375  0.125     ]
 [0.54492188 0.05208333 0.0703125  0.1484375 ]]
[[0.49023438 0.13539192 0.09765625 0.17102138]]
[[0.16992188 0.10542169 0.22265625 0.24623494]
 [0.60253906 0.08358434 0.21484375 0.25150602

[[0.078125   0.22547584 0.07421875 0.14641288]
 [0.26953125 0.20497804 0.0703125  0.14348463]
 [0.42578125 0.24597365 0.07617188 0.1522694 ]]
[[0.265625   0.31470588 0.11132812 0.23529412]
 [0.54492188 0.35882353 0.13867188 0.27941176]]
[[0.27929688 0.10013908 0.21679688 0.64534075]
 [0.48828125 0.10013908 0.23046875 0.65368567]]
[[0.515625   0.50520833 0.0546875  0.109375  ]]
[[0.34765625 0.3270073  0.16015625 0.4729927 ]
 [0.47851562 0.33576642 0.17773438 0.46715328]]
[[0.64355469 0.13020833 0.06835938 0.15798611]
 [0.46386719 0.18229167 0.06347656 0.14756944]
 [0.28027344 0.19270833 0.06445312 0.13715278]
 [0.09277344 0.06076389 0.06347656 0.171875  ]
 [0.80859375 0.11979167 0.05273438 0.15451389]]
[[0.04394531 0.34309896 0.39160156 0.42513021]
 [0.31542969 0.28059896 0.53222656 0.41536458]]
[[0.46484375 0.13020833 0.17578125 0.33854167]]
[[0.24316406 0.16037063 0.05566406 0.085531  ]
 [0.61230469 0.10121169 0.07226562 0.09978617]]
[[0.3203125  0.17708333 0.08789062 0.21875   ]
 [0.

[[0.12207031 0.21653255 0.21386719 0.22238478]]
[[0.45996094 0.0412758  0.12207031 0.11507192]
 [0.69238281 0.0819262  0.12207031 0.10131332]]
[[0.25976562 0.22064777 0.24902344 0.21255061]]
[[0.27734375 0.10363086 0.10351562 0.11497731]]
[[0.12304688 0.209375   0.27929688 0.625     ]
 [0.57617188 0.159375   0.3125     0.553125  ]]
[[0.70898438 0.52929688 0.10546875 0.12695312]]
[[0.52539062 0.19726562 0.17578125 0.12890625]]
[[0.31054688 0.18174847 0.35058594 0.38496933]]
[[0.51171875 0.18164557 0.17773438 0.1835443 ]]
[[0.20117188 0.04166667 0.10742188 0.19010417]
 [0.62304688 0.21614583 0.09179688 0.19010417]]
[[0.47265625 0.42925278 0.1328125  0.27980922]]
[[0.36328125 0.09375    0.11523438 0.22916667]
 [0.15429688 0.33333333 0.15625    0.23697917]
 [0.36328125 0.3515625  0.13867188 0.28385417]
 [0.51367188 0.296875   0.13671875 0.24739583]
 [0.74023438 0.3046875  0.16210938 0.24479167]]
[[0.40039062 0.32291667 0.08007812 0.13541667]
 [0.50585938 0.359375   0.06054688 0.1015625 ]]


[[0.45507812 0.10515873 0.09179688 0.08597884]]
[[0.11523438 0.06415621 0.09570312 0.09553696]
 [0.23535156 0.07601116 0.07128906 0.07391911]
 [0.3359375  0.09344491 0.08203125 0.08228731]
 [0.453125   0.05439331 0.12792969 0.11506276]
 [0.609375   0.10529986 0.0546875  0.06624826]]
[[0.50585938 0.03131313 0.15429688 0.11515152]]
[[0.40722656 0.07237814 0.17871094 0.11521418]]
[[0.16308594 0.04875    0.0546875  0.08625   ]]
[[0.41210938 0.11148649 0.12109375 0.13648649]]
[[0.4609375  0.0428195  0.12207031 0.09749671]]
[[0.3828125  0.07979502 0.11425781 0.13469985]]
[[0.31542969 0.16594828 0.18261719 0.18318966]]
[[0.37304688 0.06640625 0.13378906 0.165625  ]]
[[0.39257812 0.14431586 0.13964844 0.12525528]]
[[0.13867188 0.04492188 0.09179688 0.12890625]
 [0.57421875 0.09179688 0.16992188 0.234375  ]]
[[0.20117188 0.05483271 0.07128906 0.0901487 ]
 [0.70898438 0.05855019 0.07617188 0.09200743]]
[[0.37988281 0.0879397  0.109375   0.10364322]]
[[0.234375   0.046875   0.05664062 0.08007812]

[[0.578125   0.3042623  0.15429688 0.11934426]]
[[0.19140625 0.00206612 0.31054688 0.21280992]]
[[0.3828125  0.06242038 0.14941406 0.13057325]]
[[0.40722656 0.07421875 0.12597656 0.11523438]]
[[0.44824219 0.06222548 0.16699219 0.16983895]]
[[0.4375     0.11111111 0.0703125  0.14236111]]
[[0.390625   0.25767309 0.07519531 0.07209136]]
[[0.38574219 0.05663305 0.10839844 0.10938712]]
[[0.46289062 0.04659014 0.11328125 0.11748818]]
[[0.23242188 0.20318725 0.48535156 0.44156707]]
[[0.22265625 0.06051122 0.13867188 0.09963485]]
[[0.36425781 0.07198444 0.30566406 0.31063554]]
[[0.39453125 0.06441948 0.17578125 0.19550562]]
[[0.45019531 0.12134977 0.2734375  0.27774173]]
[[0.45605469 0.06420852 0.11132812 0.11760966]]
[[0.43261719 0.08375635 0.1171875  0.12309645]]
[[0.42089844 0.18215962 0.06347656 0.0741784 ]]
[[0.41113281 0.04081633 0.13476562 0.11493018]]
[[0.21484375 0.01726264 0.08398438 0.1405672 ]
 [0.72070312 0.03699137 0.08007812 0.13563502]]
[[0.45117188 0.07421875 0.26074219 0.2519

[[0.30859375 0.28492393 0.140625   0.28492393]]
[[0.34667969 0.33542538 0.0625     0.06834031]
 [0.5546875  0.29428173 0.07421875 0.07252441]]
[[0.20800781 0.10175695 0.29980469 0.27745242]]
[[0.19921875 0.31633987 0.13671875 0.24052288]
 [0.7109375  0.26143791 0.12109375 0.2875817 ]]
[[0.453125   0.12703583 0.12890625 0.09381107]]
[[0.29589844 0.18551724 0.50292969 0.36689655]]
[[0.47949219 0.17950889 0.11035156 0.12277731]]
[[0.26367188 0.14453125 0.48339844 0.5265625 ]]
[[0.38867188 0.1        0.05664062 0.08484848]]
[[0.25390625 0.09538462 0.078125   0.2       ]
 [0.61523438 0.15384615 0.06835938 0.15692308]
 [0.78515625 0.06461538 0.07421875 0.16923077]]
[[0.390625   0.1234472  0.20410156 0.22282609]]
[[0.53222656 0.08223201 0.12695312 0.14610866]]
[[0.14453125 0.15294118 0.078125   0.17352941]]
[[0.37207031 0.04882812 0.18457031 0.203125  ]]
[[0.33984375 0.08491947 0.1171875  0.27232796]]
[[0.40039062 0.18448023 0.171875   0.35139092]]
[[0.60546875 0.26933333 0.06542969 0.0646666

[[0.30664062 0.01486989 0.38476562 0.9739777 ]]
[[0.32226562 0.37630208 0.04199219 0.07291667]
 [0.60253906 0.31510417 0.05078125 0.08723958]]
[[0.69140625 0.27083333 0.10351562 0.14583333]]
[[0.1640625  0.1124183  0.19726562 0.41045752]
 [0.80273438 0.10718954 0.11914062 0.21176471]]
[[0.67773438 0.02496879 0.13867188 0.21473159]]
[[0.60351562 0.07624633 0.1484375  0.29032258]]
[[0.44726562 0.03125    0.14648438 0.36805556]]
[[0.31835938 0.12304688 0.29492188 0.421875  ]]
[[0.18945312 0.33382138 0.10742188 0.16983895]
 [0.4453125  0.1317716  0.09765625 0.21083455]
 [0.68164062 0.21376281 0.10742188 0.22547584]]
[[0.36523438 0.35751295 0.10351562 0.32124352]]
[[0.18359375 0.27192982 0.0859375  0.15204678]
 [0.42382812 0.16959064 0.09375    0.19883041]
 [0.67773438 0.19883041 0.08789062 0.1871345 ]]
[[0.22265625 0.24305556 0.21679688 0.58333333]]
[[0.421875   0.22064057 0.15625    0.32740214]]
[[0.18847656 0.28877005 0.06445312 0.08770053]
 [0.57324219 0.28877005 0.05664062 0.07379679]


[[0.13085938 0.0556369  0.39453125 0.88433382]]
[[0.11425781 0.16617862 0.5546875  0.54099561]]
[[0.37109375 0.03812317 0.13476562 0.26099707]]
[[0.11132812 0.16666667 0.36914062 0.83333333]
 [0.5625     0.07986111 0.375      0.90277778]]
[[0.31445312 0.11458333 0.0859375  0.33333333]]
[[0.26171875 0.14852941 0.52636719 0.51691176]]
[[0.07421875 0.00695652 0.2890625  0.59478261]]
[[0.4453125  0.56640625 0.13867188 0.27734375]]
[[0.52929688 0.17505995 0.22851562 0.38369305]]
[[0.37695312 0.152513   0.2734375  0.67590988]]
[[0.49023438 0.2349486  0.09960938 0.22320117]]
[[0.4140625  0.16176471 0.25390625 0.24779412]]
[[0.29980469 0.03296703 0.70019531 0.67765568]]
[[0.35546875 0.234375   0.27929688 0.51302083]]
[[0.68066406 0.1875     0.13183594 0.23242188]]
[[0.1640625  0.09144111 0.22949219 0.25749817]]
[[0.39160156 0.11550941 0.23242188 0.23231668]]
[[0.078125   0.16983895 0.45019531 0.48243045]]
[[0.26953125 0.17549407 0.44824219 0.48379447]]
[[0.32226562 0.015625   0.18359375 0.4375

[[0.4296875  0.13872832 0.21972656 0.28323699]]
[[0.63476562 0.09179688 0.10546875 0.13085938]]
[[0.65820312 0.06442167 0.12695312 0.23718887]
 [0.26171875 0.40995608 0.14257812 0.21961933]]
[[0.29296875 0.11805556 0.09375    0.26041667]
 [0.59375    0.07986111 0.10546875 0.25      ]]
[[0.54003906 0.1208577  0.20507812 0.18908382]]
[[0.55273438 0.13802083 0.1875     0.32552083]]
[[0.2265625  0.35677083 0.078125   0.140625  ]
 [0.44335938 0.34114583 0.08203125 0.14322917]
 [0.72460938 0.40885417 0.07617188 0.13541667]]
[[0.79003906 0.11419753 0.05078125 0.23148148]
 [0.40917969 0.11419753 0.04492188 0.23148148]
 [0.09765625 0.10802469 0.04492188 0.23765432]]
[[0.37402344 0.10784314 0.21777344 0.2753268 ]]
[[0.29199219 0.11502516 0.22265625 0.23436377]]
[[0.1640625  0.33764368 0.26757812 0.21623563]]
[[0.625      0.03119584 0.12304688 0.29462738]]
[[0.75585938 0.11127379 0.05859375 0.12591508]
 [0.49609375 0.18740849 0.0546875  0.12005857]
 [0.2734375  0.14934114 0.0625     0.0966325 ]]


[[0.50390625 0.18763326 0.33007812 0.30277186]
 [0.08007812 0.20469083 0.2578125  0.23383085]
 [0.34082031 0.06609808 0.16308594 0.16773276]
 [0.30566406 0.56218905 0.43164062 0.20326937]]
[[0.3125     0.0626151  0.39941406 0.55801105]]
[[0.24902344 0.13300142 0.08007812 0.08036984]
 [0.53613281 0.08036984 0.08886719 0.09743954]]
[[0.3828125  0.24798387 0.24414062 0.32459677]]
[[0.41992188 0.09722222 0.27929688 0.70486111]]
[[0.59960938 0.11939268 0.13769531 0.14423741]]
[[0.29589844 0.17933723 0.30175781 0.22417154]]
[[0.36328125 0.15010142 0.15234375 0.13049358]]
[[0.39160156 0.1732899  0.22558594 0.21824104]]
[[0.6640625  0.10164425 0.33398438 0.70254111]
 [0.1796875  0.0328849  0.35742188 0.7264574 ]]
[[0.18945312 0.23987539 0.09765625 0.28037383]
 [0.27929688 0.47975078 0.0703125  0.15264798]
 [0.51757812 0.14330218 0.12304688 0.28971963]
 [0.70117188 0.34579439 0.11328125 0.23676012]]
[[0.84765625 0.36176471 0.0703125  0.10882353]]
[[0.34375    0.05273438 0.33398438 0.4609375 ]]


[[0.44335938 0.09775429 0.140625   0.28533686]]
[[0.140625   0.14985591 0.12890625 0.25072046]]
[[0.3046875  0.23177083 0.16992188 0.25520833]]
[[0.3046875  0.15494792 0.04980469 0.08984375]
 [0.22265625 0.53515625 0.06054688 0.09895833]
 [0.42382812 0.19791667 0.05175781 0.08072917]
 [0.48828125 0.46484375 0.0546875  0.09765625]
 [0.58300781 0.17708333 0.04882812 0.08072917]
 [0.73144531 0.18098958 0.05273438 0.09114583]]
[[0.45507812 0.07583333 0.20117188 0.19916667]]
[[0.07421875 0.18832891 0.09570312 0.22281167]
 [0.2109375  0.25729443 0.10351562 0.22015915]
 [0.45117188 0.20954907 0.08398438 0.17771883]
 [0.59765625 0.19363395 0.11328125 0.19098143]
 [0.73046875 0.16976127 0.09375    0.19363395]
 [0.86328125 0.16710875 0.09375    0.20689655]]
[[0.24414062 0.22887701 0.265625   0.38074866]
 [0.52929688 0.20534759 0.25195312 0.35935829]]
[[0.28125    0.09814324 0.16015625 0.34217507]]
[[0.39550781 0.16032211 0.171875   0.16398243]]
[[0.20214844 0.17604618 0.04101562 0.08225108]
 [0.

[[0.22949219 0.17331499 0.41796875 0.39202201]]
[[0.30566406 0.16408935 0.23242188 0.23969072]]
[[0.34570312 0.1328125  0.24316406 0.1875    ]]
[[0.36621094 0.17154812 0.32519531 0.31380753]]
[[0.40039062 0.12868633 0.22753906 0.19101877]]
[[0.15429688 0.04308202 0.08496094 0.10521955]
 [0.36523438 0.15824358 0.08007812 0.09362055]
 [0.53515625 0.15824358 0.08007812 0.08782104]
 [0.8046875  0.11350456 0.08007812 0.09527755]]
[[0.35546875 0.14072633 0.21777344 0.16407263]
 [0.65625    0.15629053 0.11132812 0.14072633]
 [0.83789062 0.23605707 0.09667969 0.16018158]]
[[0.25488281 0.13257066 0.30566406 0.28129206]]
[[0.40625    0.16223232 0.4296875  0.38286827]]
[[0.3359375  0.17604618 0.28613281 0.3008658 ]]
[[0.15332031 0.1640178  0.55566406 0.49459631]]
[[0.22851562 0.16129032 0.18554688 0.40762463]
 [0.06835938 0.30498534 0.10742188 0.26099707]
 [0.4375     0.68914956 0.08007812 0.19648094]
 [0.81054688 0.23753666 0.17773438 0.3372434 ]]
[[0.33398438 0.165625   0.29492188 0.3296875 ]]


[[0.15527344 0.234375   0.58984375 0.54361979]]
[[0.1875     0.19902518 0.58886719 0.66206336]]
[[0.046875   0.06404658 0.4296875  0.87918486]]
[[0.4453125 0.13125   0.171875  0.4      ]]
[[0.34667969 0.1248366  0.41992188 0.38627451]]
[[0.39453125 0.18899676 0.27929688 0.25372168]]
[[0.27148438 0.16581446 0.41992188 0.44704164]]
[[0.33007812 0.10541728 0.13085938 0.23426061]]
[[0.32617188 0.09150327 0.28320312 0.27908497]]
[[0.26953125 0.11906311 0.15820312 0.12687053]
 [0.64550781 0.09954457 0.16113281 0.13467794]]
[[0.30078125 0.14276402 0.28027344 0.22229465]]
[[0.41015625 0.15234375 0.27050781 0.30625   ]]
[[0.3515625  0.0779681  0.16113281 0.14648553]]
[[0.1171875  0.22258274 0.49121094 0.44970798]]
[[0.27636719 0.27792208 0.48535156 0.40844156]]
[[0.33789062 0.28181818 0.31445312 0.25844156]]
[[0.29003906 0.15833974 0.40722656 0.4319754 ]]
[[0.31347656 0.17620751 0.25976562 0.28533095]]
[[0.36816406 0.18306189 0.22558594 0.18697068]]
[[0.42480469 0.11728395 0.15527344 0.14609053

In [17]:
from shutil import copyfile
from pathlib import Path

def create_dataset(data,dataset_type):
    if dataset_type == 'train':
        Images_folder = train_Images_folder
    else:
        Images_folder = test_Images_folder
    
    images_path = Path(data_folder+'/Images/'+dataset_type)
    images_path.mkdir(parents=True, exist_ok=True)
    labels_path = Path(data_folder+'/labels/'+dataset_type)
    labels_path.mkdir(parents=True, exist_ok=True)
    
    name = 1
    for path in data:
        copyfile(Images_folder+path, images_path/(str(name)+'.jpg'))
        with open(labels_path/(str(name)+'.txt'),'w') as out_file:
            for bbx in data[path]:
                x,y,w,h = [float(i) for i in bbx]
                out_file.write('1 '+str(x+w/2)+' '+str(y+h/2)+' '+str(w)+' '+str(h)+'\n')
        name+=1

In [19]:
create_dataset(train_data,'train')

In [18]:
create_dataset(test_data,'test')

In [24]:
def draw_bounding_boxes(im, bbxs,color='red',width=3):
    draw = ImageDraw.Draw(im)
    l,w,_ = [float(i) for i in np.array(im).shape]
    for box in bbxs:
        x0 = (box[1]-box[3]/2)*w
        y0 = (box[2]-box[4]/2)*l
        x1 = (box[1]+box[3]/2)*w
        y1 = (box[2]+box[4]/2)*l
        draw.rectangle([x0,y0,x1,y1], fill=None, outline=color, width=width)
    return(im)

image_name = '1600'
bbxs = []
with open(data_folder+'/labels/train/'+image_name+'.txt', 'r') as file:
    while True:
        line = file.readline()
        if not line: break
        line = np.fromstring(line, dtype=float, sep=' ')
        
        bbxs.append(line)

im = Image.open(data_folder+'/Images/train/'+image_name+'.jpg')
im = draw_bounding_boxes(im,bbxs)
im.show()